blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/NovoaDev/Business-Central-Table-Viewer/discussions
    about: Please ask and answer questions here.